version: '3.3'
services:
  postgres:
    container_name: postgres-ldiploma
    image: postgres
    ports:
      - 5460:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: diplom
    networks:
      - ldiploma

  php-fpm:
    container_name: php-fpm-ldiploma
    build:
      context: ./build/php-fpm
      dockerfile: Dockerfile
      args:
        - XDEBUG_MODE
        - XDEBUG_CLIENT_HOST
    environment:
      - SYMFONY_ENV
      - PHP_IDE_CONFIG
    ports:
      - 9612:9000
    volumes:
      - ./symfony:/var/www/symfony:cached
      - ./logs/symfony:/var/www/symfony/var/log:cached
      - ./ldiploma/:/var/www/ldiploma/:delegated
    depends_on:
      - postgres
    networks:
      - ldiploma
    command: sh -c "composer install && php bin/console doctrine:migration:migrate --no-interaction && php bin/console create:user:admin && php-fpm"


  nginx:
    image: nginx:latest
    container_name: nginx-ldiploma
    ports:
      - 8560:80
    depends_on:
      - php-fpm
    networks:
      - ldiploma
    volumes:
      - ./build/nginx/local:/etc/nginx/conf.d/
      - ./build/nginx/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf
      - ./ldiploma/public:/var/www/ldiploma/public:rw,cached

networks:
  ldiploma:
